server:
  port: ${PORT:8080}
spring:
  application:
    name: Calculator-API
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000
random-org:
  base-url: https://api.random.org/json-rpc/4/invoke
  api-key: ${RANDOM_ORG_API_KEY}
  timeouts:
    connect-ms: 3000
    read-ms: 5000
    write-ms: 5000
  feign-logger-level: basic
logging:
  level:
    feign: INFO
    com.fontolan.calculator.infrastructure.external.randomorg.RandomOrgFeign: INFO