server:
  port: ${PORT:8080}
spring:
  application:
    name: Calculator-API
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000